### ISSUE TITLE
Faker: deactivate to_str in integer 

### ISSUE THREAD

**Issue by dankor** [GitRoko/meta-data-editor#40]
to_srt will be defined by json_type. It makes no sense to toggle to_str checkbox.

**Comment by GitRoko** [comment]
Now, if json_type is string  - toggle disabled with value true, else if  json_type is number  - toggle disabled with value  false.

<img width="905" alt="Снимок экрана 2022-10-05 в 17 10 33" src="https://user-images.githubusercontent.com/35900365/194081939-07031c2d-bd15-4680-9780-7f9f44784277.png">
<img width="895" alt="Снимок экрана 2022-10-05 в 17 12 18" src="https://user-images.githubusercontent.com/35900365/194082130-1135cd28-e991-4997-be5c-be07de643875.png">

**Comment by GitRoko** [comment]
Done.
