### ISSUE TITLE
File list sidebar

### ISSUE THREAD

**Issue by GitRoko** [GitRoko/meta-data-editor#7]
- Replace file picker with directory picker.
- Open all *.yaml files a list the, for instance:
![image](https://user-images.githubusercontent.com/35900365/170831037-77821000-2c8e-4554-a624-a96a61c06c3c.png)

- List only file names (without extensions).
- The sidebar should be scrollable if it's a long list
- The sidebar should be collapsible (for instance: https://codepen.io/DeolaJ/pen/xvjbKY)

**Comment by dankor** [comment]
Done.
